# Generated by Django 5.2.9 on 2026-01-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistsignup',
            name='created_at',
        ),
        migrations.AddField(
            model_name='waitlistsignup',
            name='farming_type',
            field=models.CharField(choices=[('crop', 'Crop Farming'), ('livestock', 'Livestock Farming'), ('mixed', 'Mixed Farming'), ('other', 'Other')], default='crop', max_length=50),
        ),
    ]
