# Generated by Django 5.2.9 on 2026-01-02 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0002_remove_waitlistsignup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistsignup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waitlistsignup',
            name='farming_type',
            field=models.JSONField(default=list),
        ),
    ]
