# Generated by Django 6.0 on 2026-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapp', '0003_waitlistsignup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistsignup',
            name='email',
            field=models.EmailField(default='pending@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
